name: Generate Tetris Contribution Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Contribution Visualization
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          github_user_name: aishide
